name: freeze
description: Freeze renders by showing an image instead of the rendered widget to reduce element tree counts
version: 1.0.0
homepage: https://github.com/ArcaneArts/freeze
environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1